### ISSUE TITLE
Redo Skin Config Naming Conventions

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#101]
The way that the skins in this project are named is sort of odd. Rather than using the full names, I decided to use just the type of gadget it was (e.g. 'CPU', or 'Disks') for the config name, as well as the actual skin file's name. This hasn't been an issue until I switched to VSCode, and some of the folders have special meanings there that cause all sorts of problems with various linters and such. Thus, I think it's time to standardize them.

This will mostly be a straightforward process. However, it will require changing the config path variables. In theory, this shouldn't be a problem, because just changing the variables will change every instance of them across the suite. But if somewhere in the suite, the variables weren't used, then it will cause issues that will have to be manually fixed.

## New Conventions
- Config folders and skin INI files will use the full gadget name, but without spaces (e.g. 'CPU.ini' -> 'CpuMeter.ini')
- Individual gadget settings skins will be moved to the respective gadget's folder (e.g. 'Config\CPU\Config.ini' -> 'CpuMeter\Settings\CpuMeterSettings.ini') (still deciding on this one)
- The general settings skins (gadget manager, setup, etc.) will remain in their current folder, but it will be renamed from 'Config' to 'Settings'
- Settings skins will get their own names (e.g. 'Config.ini' -> 'CpuMeterSettings.ini')

This should alleviate the confusion I have had when developing the suite, and makes much more sense overall.

## To-do
- [x] Rename folders
- [x] Rename skin INIs
- [x] Move settings skins to gadget folders and rename the files
- [x] Rename general settings skins
- [x] Change all path variables in the StyleSheet
- [x] Fix all remaining instances of broken paths

**Comment by raiguard** [comment]
Done.
