### ISSUE TITLE
Sidebars

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#106]
Sidebar Areas will designate columns of a monitor that will be dedicated to the gadgets. What this means is that when you maximize a window, the window will not overlap the gadget, instead leaving them visible. You can designate two separate columns, either on both sides of a monitor, or on two monitors.

Additionally, you will be able to set a background for the sidebars. This drastically improves the look when a window is maximized, but when empty, can be an eyesore. Thus, a specialized invisible skin will check for maximized windows in the pertaining monitor, and will only enable the background then.

## To-do
- [x] Implement basic meters
- [x] Debug settings
- [x] Incorporate into global settings skin
- [ ] Add conditions for auto-fixing when the work area is changed

**Comment by sinankizar** [comment]
I have a problem with these sidebar thing... I have disabled it because I am using gadgets on my second monitor and constantly visible. But now on my default monitor there is an invisible area like I enabled the sidebar. Even deleted the whole skin but the space is always there... How to remove the nuisance? Thank you...

**Comment by raiguard** [comment]
State of this:

I am not happy with the way the settings are working currently. Having to manually click "update work area" is not intuitive or user-friendly. I am considering some options, including making a separate setup interface for them.

There are two issues with the sidebars themselves that have yet to be solved:

- Need to provide an easy way to reset if the work area is changed
- The performance of the Pixel color plugin on my PC is horrendous

**Comment by raiguard** [comment]
What do you mean? Is it making maximized windows overlap it?

**Comment by Shrekmachine** [comment]
It is weird, now I can't reproduce it. I cheated it now for demonstration purpose with an editor. Furthermore I noticed that WIN arrow left/right is not working properly anymore. I can't push the second window to the right side of the screen. 
![image](https://user-images.githubusercontent.com/8019511/51091769-5d9f6480-178f-11e9-8f66-f2f7fbce9b6b.png)

**Comment by Shrekmachine** [comment]
Now the real one happened again 
![image](https://user-images.githubusercontent.com/8019511/51091872-e66ad000-1790-11e9-9533-2b277876c092.png)

**Comment by raiguard** [comment]
Hm. It definitely overwrote the vertical work area. That is odd, I thought I made sure it couldn't do that. I'll take a look and get back to you...

**Comment by Shrekmachine** [comment]
I try to find a pattern to reproduce. Not that easy. Sometimes it is even when I start the desktop directly after login without any interaction. sometimes all is working as expected

**Comment by Shrekmachine** [comment]
![image](https://user-images.githubusercontent.com/8019511/51441919-0f321e80-1cd7-11e9-97ce-21ff8db67d96.png)
Does this have to do with it?

**Comment by raiguard** [comment]
Yes, thank you for the log. Just to be sure, after enabling the sidebar, did you click "update work area"?

And by the way, if you chose a similar color to your desktop to make it not show up, you can literally just disable the background by unchecking "enable sidebar 1" without clicking "update work area". It'll leave the gadgets uncovered when a window is maximized without invoking the background.

**Comment by raiguard** [comment]
![2019-01-20 10_05_49-](https://user-images.githubusercontent.com/3515394/51442547-2226fd80-1c9b-11e9-9183-a9393cee875d.png)

I can make this happen by enabling the sidebar without clicking "update work area". However, I cannot reproduce the log errors you're seeing.

**Comment by Shrekmachine** [comment]
I did not probably click "update work area" as a last action agter I experimented with the sidebars. Did that now plus unticking "update work area". Works for now :)

**Comment by raiguard** [comment]
Yeah, that was probably it. As I said before, I'm not happy with the way the sidebar settings interface turned out, so I'm going to redesign it.

While I have you here, are you experiencing any lag spikes when using Network Meter? I have began to get those in the last two days, and want to see if it's just my PC or not.

Thanks for all of your feedback and testing. :)

**Comment by raiguard** [comment]
The new sidebar settings interface will be separated, with a focus on configuring, THEN applying the settings. This is different from normal settings, which are applied on-the-fly. Therefore, it will be its own separate skin, contained in `Settings\Sidebars\Setup`.

While configuring, another skin will appear as a "preview" of where the sidebar is going to go, and what it will look like. This will make setup a lot more intuitive and user-friendly.

Once the user has configured the sidebar, they will click the "apply settings" button, which will update the desktop work area and enable the sidebar skins.

I think this will be a lot better than the current method, which is quite confusing and unclear.

**Comment by Shrekmachine** [comment]
cool!

**Comment by Kimpalon** [comment]
Very nice. I was just about to report the same issue. Using the skin on second screen, taskbar covered on first screen. Win+arrows not working properly (I saw your reply on that). New setup expercience looks dope. Love the skin

**Comment by raiguard** [comment]
So I am finally almost finished with the new setup experience. It took a while to find a good flow to it, but I think it's finally there. Here's a preview:

![new sidebar setup](https://user-images.githubusercontent.com/3515394/52907084-4c76c700-3217-11e9-9a4f-fc0d9c85d12a.gif)

There are still a few things left to do before it'll be 100% done:
1. Fix putting more than one sidebar on a monitor not working at all (when you configure the second sidebar it will overwrite the first sidebar's work area, so you can only see one at a time)
2. Add a notification (can be disabled) when the work area is reset, to allow you to refresh Rainmeter with the click of a button

**Comment by raiguard** [comment]
You can now successfully put two sidebars on one monitor! It only required redesigning the entire work area setting measure... that took three hours!

![2019-02-16 21_10_43](https://user-images.githubusercontent.com/3515394/52908269-7b993280-322f-11e9-9eb6-e8a65cf4ce95.png)

**Comment by raiguard** [comment]
I realized after trying that adding a notification when the work area is screwed up is horrendously difficult. So I'm just going to rely on mentioning in the sidebar tutorial that you'll need to refresh Rainmeter when that happens.

Anyway, v1.5.0-beta.10 is released, so this is FINALLY DONE! :D

**Comment by Kimpalon** [comment]
Downloaded latest rainmeter beta and MG 1.5.0-rc.1 and have this issue now. I use it on my second screen. Windows that are maximized take on this size. The issue with covering the taskbar on my first screen is gone.
![sidebar](https://user-images.githubusercontent.com/47331102/53244187-69454b80-36aa-11e9-95cd-2cd29caa0fb4.png)

**Comment by raiguard** [comment]
O.o

Disable all of your sidebars and see if that fixes it. If it does, try setting them up again. If it doesn't, right-click on Rainmeter's tray icon, click `Edit Settings`, and delete all of the `DesktopWorkArea` keys. Then restart Rainmeter.

**Comment by Kimpalon** [comment]
Resets the fullscreen, any time a apply the sidebar it does it again.

**Comment by raiguard** [comment]
Thank you for the information. This has (hopefully) been fixed for v1.5.0-rc.2.

**Comment by Kimpalon** [comment]
You are correct sir, issue gone with rc.2.
