### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#112]
So I need to be a bit transparent here: I only have a few more months that I can work on this project, after which I will be leaving for two years on a religious service mission. As such, there will only be a few more updates before the hiatus begins:

#### Chronometer (#35)
- [x] Event countdown(s?)
- [x] Timers and alarms
- [x] Proper time locale support (#110)
#### Network Meter
- [x] Proper network interface configuration
- [x] WiFi information (#95)
- [x] Distinguish between LAN and not connected at all (#95)
#### New Gadgets
- [x] Audio Meter (#92)
- [x] Weather Meter (#93)
#### General
- [x] Sidebars (#106)
- [x] Skin scaling (#33)

#### New Gadgets
- [x] Calendar
- [x] Battery Meter
- [x] Clipboard Meter
#### General
- [x] Convert to FontAwesome / icon standardization (#146)
- [x] Update settings system / implement ColorPickerPlus (#147)

More to come...

**Comment by DrYSG** [comment]
Love the new version. One small request. I use it on my Surface Pro, and I really need a battery meter. Is that a big effort? The illustro Pulsar that I am using now really does not fit in with the rest of your gadgets..

**Comment by raiguard** [comment]
It'll come with v1.6, along with all of the other gadgets planned for that version. If you want to gain early access to it, click the "opt-in to development testing" button in the global settings skin.

**Comment by raiguard** [comment]
Holy crap, I can't believe it. v1.5 is functionally complete! I technically started working on this release back in July of last year (!!!) while waiting for stangowner to finish the new SMV for v1.4. It's been a long time coming, but it's by far my biggest release yet! I'm really proud of how it turned out.

I'm going to fix a few outstanding issues, and create a default layout that will be shipped with the suite, then release v1.5.0-rc.1. Hopefully it'll be officially released the week after!

**Comment by Shrekmachine** [comment]
> Holy crap, I can't believe it. v1.5 is functionally complete! I technically started working on this release back in July of last year (!!!) while waiting for stangowner to finish the new SMV for v1.4. It's been a long time coming, but it's by far my biggest release yet! I'm really proud of how it turned out.

Wohooo! Thanks for all your efforts

**Comment by raiguard** [comment]
Well, v1.5.0 is now packaged and uploaded to GitHub. I'm going to wait until tomorrow night to release it, just in case any last-minute issues crop up. But if all goes well, it will be released tomorrow night, and I'll be able to move on to broader horizons, AKA v1.6! :D

**Comment by Shrekmachine** [comment]
>  I only have a few more months that I can work on this project
So you will continue to work on this? A little selfish but I think it is a good idea not to stop the development.

**Comment by raiguard** [comment]
Yeah, originally I was going to be gone by now, but medical stuff happened so that got delayed. I'm not going to be leaving until May or June now.

**Comment by raiguard** [comment]
Once I'm gone I won't have access to the internet for two years, but I'll be back in full swing once I return. I'll keep adding stuff until I run out of ideas. :D

**Comment by Shrekmachine** [comment]
Wow, that sounds like a serious and tough decision. Hopefully you will have a great time.
A pity that this will not be further continued. Maybe you find someone working on a fork?

**Comment by raiguard** [comment]
Yeah, it'll be tough. Luckily my time will be full of work and doing service, so I wouldn't have time to do other things anyway. It'll be worth it.

I'm going to give repository access to someone I trust so they can update MG if a Rainmeter update seriously breaks something, but they won't add any new features (probably). I haven't decided who I will give it to yet though.

**Comment by jlvrhee** [comment]
Thanks for all the work !!
It only reports my cpu fan currently. Would it be possible to add an extra entry to also show the chassis fan RPM data?

**Comment by raiguard** [comment]
Well I'll think about it, but not right now. I'm literally releasing v1.5 right now. :D

**Comment by Shrekmachine** [comment]
> Thanks for all the work !!
> It only reports my cpu fan currently. Would it be possible to add an extra entry to also show the chassis fan RPM data?

Sounds to me like a different gadget. I would prefer to keep things with CPU which belong to CPU

**Comment by raiguard** [comment]
Yeah, I considered making a fan monitoring gadget before, but deemed it too niche. Most people don't care about their case fans. Additionally, literally every case is different, so will have different kinds of fan sensors and numbers of fans. That kind of inconsistency is very difficult to work with in Rainmeter. Sorry jlvrhee, but it's not going to happen.

**Comment by jlvrhee** [comment]
Hi raiguard, thanks for considering it and I understand your reasoning

**Comment by thamatthatter** [comment]
Hey raiguard. This is probably easy to do myself. How would I make the background transparent instead of a color?

**Comment by raiguard** [comment]
Go into global settings and click the white button next to the close button. In that file, add `,1` to the end of both the `colorBg` and `colorBgBorder` lines. Save the file, refresh your gadgets, and it would now be transparent.

**Comment by raiguard** [comment]
So after almost seven months of delays due to health complications, I finally know the exact date that I'll be leaving on my religious service mission: September 18th. After that day I will have no internet access for up to two years, so I will not be maintaining this project during that time. Once I return, however, I will still work on this project. Thanks everyone for your support!

**Comment by raiguard** [comment]
ModernGadgets is essentially finished for the foreseeable future, so I'm gonna close this!
