### ISSUE TITLE
Remove settings backups

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#114]
Now before you all get enraged at me and say, "RAIGUARD, WHY!? NOW I'LL HAVE TO REDO EVERYTHING EVERY TIME YOU UPDATE THE SUITE!"

Actually no, you won't need to do that. In fact, if all goes well, the process will be even easier than it was before: it'll happen automatically as you install the update. No backups, no importing, no potential bugs. Just pure settings bliss.

This is made possible through the [Variables files](https://docs.rainmeter.net/manual-beta/distributing-skins/) function of the skin installer. It does the exact same thing as the settings backup did: it will use any existing variable values instead of overwriting them with the defaults. My only complaint is WHY DIDN'T I KNOW ABOUT THIS FUNCTIONALITY SOONER!? IT WOULD HAVE SAVED ME SO MUCH TROUBLE!!! >:(

There is one disadvantage to this approach: it will also overwrite any changes made to the HWiNFO SMV sensor labels. But this shouldn't be an issue, because I think they're good as they are.

## To-do:
- [x] Remove settings backup code & script
- [x] Copy settings files into a 'defaults' subfolder
- [x] Change reset to defaults functionality to pull from this folder, rather than the external one
- [x] Fix welcome screen logic

**Comment by raiguard** [comment]
Done with v1.5.0-beta.1
