### ISSUE TITLE
Less intrusive update notifications

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#121]
[This topic](https://forum.rainmeter.net/viewtopic.php?f=27&t=29933) on the Rainmeter forums discusses the ability to use Windows' built-in toast notifications from Rainmeter. I want to use this to deliver the ModernGadgets update notifications on Windows 10.

For those on Windows 7 or 8, the notification will be moved to the gadget context menus. What this means is that if an update is available, it will show up at the bottom of the menu when you click a gadget's wrench icon.

Both options are designed to make the update notification less intrusive. I never intended it to become a Microsoft-esque nag, but several people have seen it as such, and I think this solution works out for everybody.

For now, both notifications will open to the relevant release page on GitHub. Hopefully in the future, you will be able to view the changelog and download the update all from the notification (on Windows 10, anyway...)

This way, the setup skin will never show up unless the user is being welcomed for the first time. Other than that, it will simply hide in the background and check for updates.

## To-do
- [x] Replace update checker skin
- [x] Replace welcome skin
- [x] Test welcome logic to make sure it works
- [x] Add settings UI for changing / disabling the notification sound

**Comment by raiguard** [comment]
Update: I decided to try and tackle this last night. Little did I know that it would only take me two hours to completely implement this! I decided against using the Win10 notifications because it would be a pain to work with, so I created my own custom banner that appears at the bottom-right of the main monitor. This works really well and I am content with it.

**Comment by raiguard** [comment]
Complete in v1.5.0-beta.6.

**Comment by raiguard** [comment]
That's weird, are you sure? The banner should disappear and the changelog viewer should appear. Could you open the Rainmeter log and tell me if it says anything?

**Comment by Shrekmachine** [comment]
The log was deactivated. How can I provoke the Update toast again?

**Comment by raiguard** [comment]
If you're still on v1.5.0-beta.5, right-click on the Rainmeter tray icon, find `ModernGadgets\Settings\Setup` in the list, and click 'Refresh skin'. The toast should then reappear.

**Comment by raiguard** [comment]
[Here](https://drive.google.com/open?id=1CN2Kdro_OYrjU-IheD_I2mdKPz_Bak1i) is a video of it working on my system (right now it's really bad quality because it's still processing, but you should get the idea).

**Comment by Shrekmachine** [comment]
I see the toast, I cklick on View Details and the toast goes away without further notice...
I'm already on beta 6, will test it again with the next release.

**Comment by raiguard** [comment]
1. Do you have multiple monitors?
2. What is the screen resolution of your main monitor?

**Comment by Shrekmachine** [comment]
> 1. Do you have multiple monitors?
No
> 2. What is the screen resolution of your main monitor?
4k (3840x2160)

**Comment by raiguard** [comment]
This is very strange. I cannot reproduce your issue even when I replicate the conditions (disabling my two side monitors, and my middle monitor is 4k). Please downgrade to beta 5 and tell me what the log says when the toast appears.

**Comment by Shrekmachine** [comment]
Tried it, now it works... weird. Only small issue is that it is hiding - like all other Rainmeter windows e.g. settings - behind eventually open windows. 
![image](https://user-images.githubusercontent.com/8019511/51784949-e5eb1580-2150-11e9-854f-dc21fdbfc093.png)

I think we can close this one.

**Comment by raiguard** [comment]
Oh, cool! Being hidden behind belt opened windows is just Rainmeter's default behavior. Thanks for all your testing and feedback!
