### ISSUE TITLE
Update Weather Meter to use Dark Sky API

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#190]
I had planned on doing this eventually, whether or not IBM decided to kill wxdata. But now that wxdata has gone down again, quite possibly forever, I think now is the time.

Weather Meter will be switched to using the [Dark Sky API](https://darksky.net/dev). For now, I am simply going to convert the existing gadget over to Dark Sky, so people can keep using it. However, once that is out, I will be rewriting Weather Meter to better take advantage of Dark Sky's features.

### To-do
- [x] Experiment with the JSON parser plugin
- [x] Implement Dark Sky into Weather Meter
- [x] Replace city search with OSM-based solution

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/72584648-21be4400-38a8-11ea-8b8e-2aa8bfa1be1b.png)

Well... that only took a few hours!

**Comment by sdholden** [comment]
Not working here, after replacing the appropriate files.

![image](https://user-images.githubusercontent.com/14812533/72630411-3e965e00-3920-11ea-8287-b550d9c4a404.png)

**Comment by sdholden** [comment]
Oh, and I put my key in and updated the lat/long for my location.  Putting the key and lat/long in a browser URL as detailed on the Dark Sky API page works fine...

Partial snip of browser window below
![image](https://user-images.githubusercontent.com/14812533/72630726-f3307f80-3920-11ea-80ca-65b0d041b981.png)

**Comment by raiguard** [comment]
You've gotta open the settings file and provide your own API key for Dark Sky. I'll be working on implementing that into the settings skin today, along with a replacement for city lookup.

**Comment by sdholden** [comment]
Yup did that.  And confirmed it works in a browser...

**Comment by raiguard** [comment]
Ah, I left it in debug mode. Open the skin file and scroll to line 100. Uncomment that line and comment the line above it. Then it should work.

**Comment by raiguard** [comment]
Also you'll have to manually install the JsonParser plugin.

**Comment by sdholden** [comment]
Bingo!

Only Imperial at the moment, as I can't select Imperial/Metric now (see earlier screenshot) as the Location filed is partially on top of the Units line...

Will find the entry in the .ini and change manually for now....

**Comment by sdholden** [comment]
Isn't immediately obvious how to force metric in the config files....is there an easy way?

**Comment by raiguard** [comment]
Yeah, I haven't added support for metric units yet, this is still an early prototype. You can change the units by adding `?units=ca` to the end of line 100. Here is the documentation:
![Screenshot_20200117-102227_Chrome](https://user-images.githubusercontent.com/3515394/72632335-4e5b7580-3913-11ea-8352-af60453b9a8d.jpg)

**Comment by sdholden** [comment]
Tried that already and it had no effect....tried ?units=auto as well.  Always imperial.
No worry, it can wait for next update.
Thx!

**Comment by raiguard** [comment]
If you update the files again you _should_ be able to easily change the units by changing the `units` variable.

**Comment by sdholden** [comment]
Yup, updating and leaving line 100 units at auto now shows metric here in Toronto!

Great work, thanks again!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/72658785-2c91db00-3973-11ea-93c1-d2584dfe1642.png)
City search is complete. It's almost ready!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/72659570-f3f7fe80-397e-11ea-892c-5398139ca059.png)
And it's done! I'll be releasing a beta tomorrow for widespread testing, but everything should work just fine.

**Comment by Shrekmachine** [comment]
Awesome

**Comment by raiguard** [comment]
I decided to just release the full patch instead of a beta, since it's _probably_ fine. Please let me know if any issues come up (which they inevitably will)!

**Comment by Stephen1R2** [comment]
I hope you are aware that the way you are useing the API is directly against Dark Sky's TOS? It's right there in the "Use of Service" section. The "Don't direct your users to sign up" part. I like your rainmeter skin and don't want to see it explode.

**Comment by raiguard** [comment]
I am aware. Unfortunately, there is _quite literally_ no other way to do it with Rainmeter. There is no way to obfuscate the API key, and even if you could, I wouldn't be able to afford the API costs since you can't charge money for skins. Trust me, I've been thinking about this for months and don't see any other way.

Other Rainmeter skins have been using Dark Sky for years without issues, so hopefully the same will hold true here.

**Comment by raiguard** [comment]
![2020-01-20 23_18_39-D__Caleb_Development_Rainmeter_Testbench_Skins_ModernGadgets_WeatherMeter_Weathe](https://user-images.githubusercontent.com/3515394/72780718-c27c6e80-3bdc-11ea-9a79-74006ca486c7.png)
Experimenting.

**Comment by Shrekmachine** [comment]
very(!) promising. I like it much more. The current weather widget is very crowded

**Comment by Caboose700** [comment]
Hopefully if this experiment goes though, you would leave the old layout alone as I quite like the extra bit of information that the current layout provides.

**Comment by raiguard** [comment]
It's not done yet, it'll have all the same information that the original does, and lots more. Just wait until you see the design I'm coming up with for the hourly forecast. :D

**Comment by sausje** [comment]
Hey,

One small issue I've got with the updated version is that the warning sign in the top left isn't going away.. I've now got flood warnings for the past 2-3 weeks, yet if I click on it, it says no warnings for the area..

**Comment by raiguard** [comment]
If it's okay with you, could you share what city you have selected? This sounds like a Dark Sky API issue.

**Comment by sausje** [comment]
Not a problem, that's Valkenburg (Limburg) in the Netherlands.

This is the warning itself: https://i.imgur.com/T1AlTFB.png

**Comment by raiguard** [comment]
Ok, so the Dark Sky API itself is at fault here. You'll just have to sit tight and wait for it to go away. Sorry about that!

**Comment by sausje** [comment]
Ah no worries, thanks for the quick reply. At least now I know where the issue lies and I'll see if I can notify them about it.
