### ISSUE TITLE
Endgame plans

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#196]
Some people following this repository may have noticed, but work on ModernGadgets has dropped off in recent months. It's finally time that I come out in full. I feel that this project is mostly complete, and I have been occupied with several other projects, most of which are Factorio mods.

There are still a few things left to do, however. This issue will list those things.

- [x] **Weather Meter Update**
  - Weather meter will be rewritten (AGAIN) to scrape the Weather.com website. Dark Sky is being deprecated, which is a massive shame, so this is the only viable way to get Weather info from now on. The weather icons will also be overhauled, because several of them have been used illegally. It will use [these icons](https://github.com/erikflowers/weather-icons) instead.
- [x] **Iconography cleanup**
  - The new Weather icons are line style, which conflicts with the rest of ModernGadgets. Where possible, icons will be changed over to their line styles in FontAwesome. For icons where the line style is illegal, a substitute from [Material Icons](https://github.com/Templarian/MaterialDesign) will be used. If the line style doesn't work for that icon, it will be left as-is.
- [x] **[Chameleon](https://forum.rainmeter.net/viewtopic.php?f=127&t=21655) support**
  - Chameleon can easily be made to work with ModernGadgets, so support for it will be added.
- [x] Miscellaneous
  - [x] More granular warnings for Battery Meter (#221)
  - [x] Remove automatic update checker and integrate update checks into the global settings skin
  - [x] Automatic external IP updating (#197)
  - [x] Multiple fans on GPU meter (#204)
  - [x] Customizable ping interval (#208)
  - [x] Use individual core clocks on CPU meter for more accuracy (#182)
  - [x] View opposite metric on Disks Meter on hover (#195)

After that, the only updates will be for bugfixes and minor QoL improvements.

**Comment by SilverAzide** [comment]
I hope you will continue to participate in the Rainmeter community!

**Comment by raiguard** [comment]
Oh don't worry, I'll still be around. I'm just not going to be adding stuff to MG anymore.

**Comment by SilverAzide** [comment]
Dark Sky has just been purchased by Apple.  New API signups are no longer being accepted and the API will be deprecated at the end of 2021.  So Dark Sky is effectively dead as of now for new users, dead for everyone by the end of next year.  :-(

https://blog.darksky.net/
https://forum.rainmeter.net/viewtopic.php?f=4&t=34918

**Comment by raiguard** [comment]
You've gotta be KIDDING ME.

It's a good thing I never got around to continuing with my redesign of Weather Meter, because it was going to heavily depend on some DarkSky-specific stuff.

Freaking Apple... I already disliked that company, but now I dislike them even more.

**Comment by SilverAzide** [comment]
> Freaking Apple... I already disliked that company, but now I dislike them even more.

LOL, my sentiments exactly.

The good news is that JSMorley created a very nice set of "include" files that will let you somewhat easily restore your previous weather.com functionality.  But it won't give you much more than what wxdata gave you earlier.

**Comment by raiguard** [comment]
Yeah, I was in the process of redesigning Weather Meter to take full advantage of Dark Sky, with an hourly forecast and some other awesome stuff... then this happens. It's actually making me really angry, more so than it should. I need to calm down.

There is no other free API that I could find that provided hourly forecasts. OWM has three-hour forecasts, but that's not nearly as nice...

**Comment by raiguard** [comment]
Updated the issue with revised plans. A complete iconography overhaul is unnecessary, because most of the icons are, in fact, legal. The only ones that were actually stolen are the weather icons. I will still be cleaning up the iconography, but most of the icons will remain FontAwesome.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/78332508-08d73d80-753d-11ea-9c91-57ab7765b921.png)
Well, that was fast. Thanks jsmorley for the pre-built measures making that absolutely painless!

Also, a preview of the new icons. :D

**Comment by raiguard** [comment]
These new weather icons are a pain... they don't have consistent margins or sizes, so I'm having to calibrate each of them manually. Now I understand why FontAwesome charges money... their icons are all standardized and consistent.

It's going to take quite a bit of time to calibrate the new weather icons, but once I'm finished, I plan on releasing them as a pack so others can use them.

**Comment by ericmassara** [comment]
> Yeah, I was in the process of redesigning Weather Meter to take full advantage of Dark Sky, with an hourly forecast and some other awesome stuff... then this happens. It's actually making me really angry, more so than it should. I need to calm down.
> 
> There is no other free API that I could find that provided hourly forecasts. OWM has three-hour forecasts, but that's not nearly as nice...

While it sucks to lose Dark Sky, if you have an API key it work until the end of 2021, according to Dark Sky's blog. When you add a new weather API service, will we still be able to keep using Dark Sky? End of 2021 is still a lot of time left on it.

**Comment by raiguard** [comment]
No, I do not plan on keeping Dark Sky in the code. The way I was using it was a legal grey-area, so I don't want that sticking around into the future anyway. Though the ethics of scraping a website are also questionable...

**Comment by FroznFoton** [comment]
@raiguard - Just wanted to chime in and mention how much I appreciate the effort you've put into this project over the years.  I've been using these on all 3 of my machines since not too long after you released them.  It was my introduction into rainmeter and helping me get a better sense of monitoring my hardware in general.  

I understand your loss of passion for this project - especially with the recent DarkSky fiasco, so I wish you the best in your future endeavors.  Just wanted to chime in and mention how much your effort on this project has benefited me.  Perhaps I will fork the project and use this as a foray into my own rainmeter customization! 😁😁😁

**Comment by raiguard** [comment]
It's been a while since I've worked on this project, but I intend to work on it now until v1.7 is done and I've fixed all outstanding bugs. I finally got the motivation to finish this.

Anyway, have a look:

![image](https://user-images.githubusercontent.com/3515394/89117669-dbec5600-d45c-11ea-900c-aae2d8b411fe.png)

There are a few differences here. First, the whole gadget now uses the latest version of jsmorley's weather.com scraping measures, which will hopefully work for a while. Additionally... SunCalc is no more. SunCalc has proven to be extremely unreliable in extreme latitudes, and the information that it provided would straight-up be tens of minutes off. TWC provides sun and moon information, so I decided to completely axe SunCalc and use the information that I'm already downloading anyway.

This does mean a few things: first, the sun/moon altitude chart (shown on hovering the gadget) is no more. The other thing that i had to remove was the moon view angle. This is a shame, because the moon view angle was really really cool, and was my favorite part of the gadget. But it was also the only part of SunCalc that was actually accurate...

I have also decided not to do a forecast at all. Instead, clicking the icon will take you to the ten-day forecast on weather.com. I was never happy with the forecast design, and so I wouldn't be happy putting it back in the way it was. But I also don't have enough motivation to redesign it. In short, it's going away permanently due to my laziness. I'm sorry.

If I get time in the future, I will see about doing a mini-forecast again. However, as I am about to graduate from school and (hopefully) get my first full-time job, I'm not sure how much free time I'll actually have between work and the other projects that I have commitments to.

Anyway, that was a long rambling update. I have knocked out quite a few to-dos today, and I'm feeling pretty good. The only things left to do for Weather Meter are fix the high temperature display (easy) and spend 20 hours fiddling with and aligning all of the new weather icons (extremely hard).

**Comment by Shrekmachine** [comment]
You have a date in mind we can expect 1.7.0?

**Comment by raiguard** [comment]
@Shrekmachine I don't want to make any promises, since I am quite an inconsistent person. But, it should be soon-ish (TM).

The biggest hurdle has been overcome: the weather icons. When I sat down to work on the icons, I realized that the icons also come in a font. This would let me `CenterCenter` align all of the images, so I wouldn't have to do any manual fiddling and SVG editing to get them to line up. While I would like to use Shape meters instead of a font, this was probably 1% of the time for 99% of the same result.

So, Weather Meter is fully functional now!

![image](https://user-images.githubusercontent.com/3515394/89131160-e7289b80-d4c7-11ea-89a2-4560cefc8a13.png)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/89131212-44bce800-d4c8-11ea-96f8-f9b7ee6558ab.png)

I will probably end up making some minor modifications to Weather Meter, but as far as I'm concerned, it is good for release at the point it's at now.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/89133542-ef89d200-d4d9-11ea-99f7-5eb72c44736f.png)

OK, I lied. _Now_ it's actually done.

**Comment by SilverAzide** [comment]
In case anyone is interested, check out [this thread on the Rainmeter forums about sun/moon data from a weather.com API](https://forum.rainmeter.net/viewforum.php?f=4&sid=5318ddbf8f2cae6e7bba2a4a4c62aa40).   Raiguard, this might allow you to keep your elevation code, but I don't think it has anything you can use for calculating the moon angle/tilt (I'm not sure what the correct astro term for that tilt angle is).  Mordasius's skins (which I swiped his Lua scripts from) have all the calcs EXCEPT that angle.  😢  His scripts give results that seem almost perfect (+/- 1 minute or less).  I haven't been able to figure out how to get your angle calc integrated into his code, but I think all the necessary bits are there somewhere.

**Comment by raiguard** [comment]
Yeah, unfortunately, that doesn't provide the needed data to get the view angle. The two things you need are the illuminated angle (the angle that the illuminated limb of the moon is pointing) and the parallactic angle is... something beyond my understanding. [Here's](https://en.wikipedia.org/wiki/Parallactic_angle) the wikipedia page on it.

SunCalc would spit both of those out in radians, so I used this formula to get the value of the `Rotate` modifier for the moon shape necessary to get the correct angle:

`-deg([&MeasureSunCalcScript:GetData('moonIllumination', 'angle')] - [&MeasureSunCalcScript:GetData('moonPosition', 'parallacticAngle')])`

Anyway yeah, I can re-implement the altitude calc now, but not the moon angle.

**Comment by sdholden** [comment]
Can someone create a release for 1.7.0 now?  Still see 1.6.3 as the official version...
Sorry to hear you're moving on, but thanks for all the hard work to get it to this point!  It's the only skin I use on several machines...

**Comment by raiguard** [comment]
I'm still developing v1.7.0, it is not ready yet. I have not "left" yet. v1.7.0 will be the last feature update, everything after that will just be maintenance and bugfixes.

**Comment by Shrekmachine** [comment]
take your time and deliver 1.6.xx versions in the meantime :D

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/90069344-6b8cd280-dcaf-11ea-9aa2-f26ddd1be139.png)

Thanks to the astro data that jsmorley discovered on weather.com, I was able to re-implement an more accurate depiction of the moon's status than I had purely with the includes. Now it retains its exact illumination value instead of being an approximation.

**Comment by SilverAzide** [comment]
I don't mean to interrupt, but I just wanted to point out that the 41% lit portion is on the other side, since we're in the waning phase now...

**Comment by raiguard** [comment]
Wait, I've had it backwards this entire time!? Oops. Thanks for pointing that out. :D

**Comment by SilverAzide** [comment]
Haha, no worries, 1.6.3 seems fine.  :-)

![WM163](https://user-images.githubusercontent.com/2706567/90078963-845baf00-dcd4-11ea-95c4-c9ebd005d489.jpg)

**Comment by aniforprez** [comment]
Oh man I was wondering what the status of the project was. I hope someone is able to contribute and keep supporting these widgets through future rainmeter and other software releases like hwinfo

But I have to say, thank you SO MUCH for the work so far. These are the most comprehensive and consistent-looking widgets with an extensive set of stats and I've installed and used them for YEARS now. This is superb work and thank you for your contribution

**Comment by raiguard** [comment]
Once again, things have happened and work stalled for a while, but this time it wasn't due to disinterest in the project.

The list of things to do is relatively small, so hopefully I can have the version finished relatively soon. Thank you all for your patience!

**Comment by raiguard** [comment]
![7d1dc200-75d6-4b0b-bbd7-a9bb69b45792](https://user-images.githubusercontent.com/3515394/103181911-a01ab880-4863-11eb-9cfb-c0b5c155458b.gif)

Vim macros are so fricking satisfying.

**Comment by raiguard** [comment]
After a few hours of focused work, the to-do list is finally done! I will be testing v1.7 for a little bit, then preparing updated screenshots and such, then it can finally be released!

I would like to apologize again for how long this has taken. I'm actually switching away from Windows entirely soon, so I'm not even using Rainmeter anymore. However, I will still fix bugs (especially around Weather Meter) and keep the suite usable for as long as Rainmeter exists.

Thank you for your support!

**Comment by SilverAzide** [comment]
Not using Rainmeter anymore???  :worried:  Who am I going to steal ideas from now?  I just switched all my skins to use ColorPickerPlus instead of RainRGB, and finally got the moon zenith angle figured out so I can get the moon tilted properly...  :sob:

**Comment by Shrekmachine** [comment]
good points. raiguard, you should reconsider...

**Comment by raiguard** [comment]
Now I'm grateful that I wrote detailed release instructions for SilverAzide, because I'm having to follow them myself! Making Rainmeter releases is such a pain... I might write a script to automate it somehow.

**Comment by raiguard** [comment]
It is... FINISHED! 🚀 🎉

**Comment by aniforprez** [comment]
Thank you so much for all the many years of updates to this wonderful gadget pack. All the best with everything
