### ISSUE TITLE
Dual GPU Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#34]
Alternate form of GPU Meter, which will support monitoring for two distinct graphics cards. Contents will be compacted to preserve as much vertical space as possible. The line graph will have four modes: GPU0 only, GPU1 only, average of the two, or disabled.

## To-do
- [x] Create new measures for GPU1
- [x] Create new meters for dual GPU mode (alternate subpage)
- [x] Add dual GPU mode toggle to config skin
- [x] Add HWiNFO configuration for GPU1
- [x] Add line graph mode switch (GPU0, GPU1, or average) (to disable, use the regular line graph toggle)

**Comment by TonyMK9068** [comment]
Any update on this? Would be a feature I'd love to see

**Comment by raiguard** [comment]
It’s still planned and will eventually happen. I simply have not had the time recently to work on ModernGadgets at all, because of IRL crap going on. But it is still in the cards.

**Comment by raiguard** [comment]
Mostly done in v1.3.0-beta.2
