### ISSUE TITLE
Chronometer

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#35]
New gadget! Will support digital and (in the future) analog time formats for main display. Includes alarms, a stopwatch, and timers, as well as a world clock, all built-in. Additionally, the main display can display the date and weekday. Also included will be system uptime and custom event countdowns (later on).

## Features
- Digital time display that can automatically match local Windows settings, or be customized
- Date display, also customizable
- Built-in stopwatch with lap support
- Three timers
- Support for up to five alarms with customizable alert sounds
- System uptime display
- Small LuaCalendar display at bottom that shows current week
- Customizable key bindings for activating stopwatch, timers
- Multiple event countdowns

## To-do
- [x] Basic meters (background, etc.)
- [x] Digital time meters
- [x] Date/weekday meters
- [x] Alarms
- [x] Stopwatch
- [x] Timers
- [x] System uptime measures/meters
- [x] Config skin

**Comment by raiguard** [comment]
So, here's the lowdown:

### Main Display
- Digital clock can be formatted either through Windows' settings or custom
- Date display is also automatic by default, but can be customized
- Small LuaCalendar snippit along the bottom, showing what day of the week it is
### Timers/Stopwatch display
- Simultaneously run three timers and a stopwatch
- Buttons for starting, pausing, resuming, and deleting timers
- Stopwatch start, lap, and stop
- Custom event countdowns
### Utilities
- System uptime
- Time Zone

The gadget's name will simply be "Clock".

**Comment by raiguard** [comment]
The initial release of Chronometer won't have all of the listed features. Those will come in subsequent updates. The initial release will include the main display, system uptime, and the stopwatch.

**Comment by raiguard** [comment]
AAAAND THE TIMER IS IMPLEMENTED! It's not pretty yet, so I'm not going to close this issue yet, but it's there and it works! :D

The Chronometer is basically finished!

**Comment by aniforprez** [comment]
Nice! Love the work you're doing with these gadgets. They look amazing and work so well

**Comment by raiguard** [comment]
Thanks! :D

**Comment by raiguard** [comment]
The proper UI for the timer is now implemented. Will be released with v1.5.0-beta.7.

**Comment by raiguard** [comment]
v1.5.0-beta.7 is released.
