### ISSUE TITLE
Standardize and simplify all settings

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#51]
The current way of doing things is just too complicated. Each gadget has a hard-coded settings script that changes settings directly pertaining to that gadget. However, this has caused complications and makes it almost impossible to create gadget variants.

So much of the settings logic will be returning to the .INI files, with the settings scripts only changing a few things. The idea is that the INI files use calc measures and variables to calculate all the settings on load, and when a setting is changed, the variables are changed, and !SetOption bangs are used to immediately enforce those changes without refreshing. This will bulk up the INIs a bit, but will make things much simpler going forward. There will be no !WriteKeyValue bangs used on the gadgets themselves anymore, which was the biggest problem with the previous way of doing things.

### To-do
- [x] Standardize functions for logging, changing variables, and updating toggle buttons
- [x] Implement new buttons (checkboxes)
- [x] Refactor CPU Meter settings
- [x] Refactor Network Meter settings
- [x] Refactor GPU Meter settings
- [x] Refactor Disks Meter settings

**Comment by raiguard** [comment]
Using this space to list changes to Disks Meter configuration:
- hideDisk variables will be used to disable/enable the measures and meters for each disk
- hideDisk will also be used to set Y positions of meters depending on their visibility
- the hideDisk variables will only be changed through the LUA script, and will be forced always to 1 if the disk is manually disabled (#31)

**Comment by raiguard** [comment]
Finished in v1.3.0-beta.1
