### ISSUE TITLE
NetMonitor support in Network Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#56]
SilverAzide added something to his gadgets that is really awesome and really useful: NetMonitor. It's a Windows service that, once installed, will constantly monitor network traffic with much higher precision than Rainmeter's built-in measures. NetMonitor will be introduced as an alternate way to get Network Meter information, and is completely optional.

### To-do
- [x] Add NetMonitor to addons folder
- [x] Create test skin for installing, enabling, pausing, disabling, and uninstalling the service
- [x] Implement that into Network Meter's settings
- [x] Add alternate measures and appropriate logic to switch between the two methods
- [x] Add toggle to Network Meter settings

**Comment by raiguard** [comment]
Done in v1.3.0-beta.2
