### ISSUE TITLE
CoreTemp and SpeedFan support in CPU Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#57]
Really should have been here from the beginning. Users will be able to use CoreTemp or SpeedFan to monitor CPU temperatures if HWiNFO is unavailable. Users will be able to select which service to use in the CPU Settings skin, with radio buttons (a new venture for me).

### To-do
- [ ] Implement alternate measures
- [ ] Implement measure switching based on setting
- [ ] Implement setting switches in settings skin

**Comment by raiguard** [comment]
So this will be done automagically, not by the user clicking a switch. This allows for the most possible information to be retrieved depending on which programs the user is running. HWiNFO is always preferred, and it will dynamically switch the measures depending on the combination of CoreTemp and SpeedFan running the user has.
