### ISSUE TITLE
HWiNFO Config Tool Updates

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#62]
The HWiNFO Config Tool needs several changes and refinements. GPU1 needs to be added, and the core readings need to not be auto-configured. Auto configuration used to work for most, but now that CPU meter supports 32 threads, the script won't be able to handle it anymore. So it will go back to being manual.

I will also take this opportunity to refine the setup tutorial a bit, and touch up the overall visual style of the config tool, and possibly add voltage readings to CPU meter.

## To-do
- [x] Make visual refinements to current elements
- [x] Add GPU1
- [x] Redo CPU Meter page to manually input values for each core
- [x] Update setup tutorial to reflect these changes

**Comment by raiguard** [comment]
The current system is giving me a headache just thinking about expanding it... It's very convoluted and poorly written. So I will be rewriting it from the ground up.

**Comment by raiguard** [comment]
Doooooonnnneeeee!!! :DD
