### ISSUE TITLE
Process Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#67]
This gadget will monitor the top ten processes by CPU usage, showing their CPU usage and RAM usage. Users will be able to specify up to five processes for constant monitoring.

The pinned processes will each have their own bar and line on the line graph, with customizable colors. The general top processes display itself will not have colors or bars.

## To-do
- [x] Essentials
- [x] Top processes display
- [ ] Pinned processes
- [x] Line graph
- [ ] Line graph and top process toggles
- [x] Compact label font toggle
- [ ] Process customization
- [ ] Color customization

**Comment by raiguard** [comment]
This gadget is postponed until a better solution for reading Top Processes is made available in Rainmeter.

**Comment by raiguard** [comment]
UsageMonitor is now live, this skin is no longer postponed!

**Comment by raiguard** [comment]
So the finished product is a much more simplified version of the original plan, but nevertheless, it is now complete!
