### ISSUE TITLE
View settings file buttons in settings skins

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#71]
Each settings skin will be getting a "view settings file" button. This is intended to let power users customize the settings more thoroughly than the typical user would do.

## To-do
- [ ] CPU Settings button
- [ ] Network Settings button
- [ ] GPU Settings button
- [ ] Disks Settings button
- [ ] Global Settings button

**Comment by SerVB** [comment]
I've added the "(view file)" button:
![image](https://user-images.githubusercontent.com/20105593/37112119-a71f8cbc-2252-11e8-98a1-ee5d8337a5b9.png)
A click here opens the `#@#Settings\GlobalSettings.inc` file. There is no design at all...

**Comment by SerVB** [comment]
Is it better to make a pull request for each button, or rename the existing PR to a common PR which is related to all buttons?

**Comment by raiguard** [comment]
I’d rename it to a common PR. Also, use the HWiNFO Config Tool’s view file button and put it up next to the close button. That was what I was going for.

**Comment by SerVB** [comment]
Actually, the `(view file)` text is too long to be shown in Network Meter Settings. It's a problem.

**Comment by SerVB** [comment]
Got it ;)

**Comment by SerVB** [comment]
Here is the result:
![image](https://user-images.githubusercontent.com/20105593/37229421-fe5cf5ca-23f4-11e8-9524-e3248ed9764b.png)![image](https://user-images.githubusercontent.com/20105593/37229385-dc029b24-23f4-11e8-9479-e5995380d3ab.png)
By the way, buttons in global settings and HWiNFO open the same file.

**Comment by raiguard** [comment]
Yeah I know they’re the same. There’s not enough global options yet to necessitate separating the files.

My only critique is that the buttons seems a bit big compared to the close button. Maybe decrease the font size by 1 and move it down so the top of the pencil is in line with the top of the close button?

**Comment by SerVB** [comment]
Hmm... I don't know what's the best:
The previous variant (`FontSize=11`):
![image](https://user-images.githubusercontent.com/20105593/37256460-2d4e0432-256c-11e8-822c-69c17096d554.png)
The size is decreased and the icon is moved down by 1 pixel:
![image](https://user-images.githubusercontent.com/20105593/37256470-4796cc84-256c-11e8-8e6d-2072969fc526.png)
The size is decreased and the icon is moved down by 2 pixels (so borders of `[edit]` and `[x]` are similar as you suggested):
![image](https://user-images.githubusercontent.com/20105593/37256465-374c0880-256c-11e8-80f7-a29255d22b0d.png)
Actually, I like first variant because centers of the square and the circle are at the same horizontal line, I even think it's perfect. Also they are the same sized just like buttons in HWiNFO Conf. Tool:
![image](https://user-images.githubusercontent.com/20105593/37256613-48f3ee70-256e-11e8-9f85-fca7862416ca.png)
But you are right -- different shapes situated nearly look a bit weird. Maybe we need a new design for the "close" button.

**Comment by raiguard** [comment]
Hmm, that icon doesn't really work next to that close button. I'll consider it and see what I can come up with.

**Comment by SerVB** [comment]
Are you going to merge my PR?..

**Comment by raiguard** [comment]
So I took a look and I think Font Size 10 looks the best aesthetically. It does not line up with the close button's margins whatsoever, but it appears to be somewhat the same size when you look at it overall.

Thanks for the input.
