### ISSUE TITLE
Replace HWiNFO Config Tool

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#73]
stangowner is currently working on a new way to configure HWiNFO sensors. The config tool will no longer be necessary, because all configuration will now take place in the SMV.

This will require a restructuring of the HWiNFO variables. The new tool will write a sensor ID, instance, and entry ID for every reading, rather than grouping them under a sensor. So all measures and meters will need to be updated to support the new variables.

## To-do
- [x] Wait for new config tool to be finished
- [x] Delete current config tool and rewrite context option action
- [x] Get the new tool working with new variables
- [x] Change variable references to match the new syntax

## Variable syntax changes
The variables will not be changing all that much. The main thing that will be changing is that every reading will have its own Sensor ID and Sensor Instance variables as well.

For example, the Core 0 Temperature measure uses `HWiNFO-CPU0-DTS-SensorID`, `HWiNFO-CPU0-DTS-SensorInstance`, and `HWiNFO-CPU0-DTS-Core0Temp` for its variables. The new syntax will require the change to using `HWiNFO-CPU0-DTS-Core0Temp-SensorID`, `HWiNFO-CPU0-DTS-Core0Temp-SensorInstance`, and `HWiNFO-CPU0-DTS-Core0Temp-EntryID`. This will be true for all other entries as well.

**Comment by raiguard** [comment]
So now Stangowner just needs to finish the tool and it'll be all set!

**Comment by raiguard** [comment]
DOOOOOOOOOOOONNNNNEEEEEEE! FINALLY!
