### ISSUE TITLE
Expand CPU Meter to support 36 threads

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#81]
The newest Intel Core i9 processors have 18 (!) cores, so CPU Meter needs to be able to display 36 threads, up from the current 32.

## To-do
- [ ] Add new meters
- [ ] Update config script
- [ ] Add new color variables and expand settings skin
- [ ] Add to Line Graph

**Comment by raiguard** [comment]
Done.
