### ISSUE TITLE
New approach to multiple GPUs

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#82]
Adding the dual GPU mode was an extensive undertaking, and is downright funky to work with. That mode will be abolished, and instead, built-in support for multiple GPU Meter skins will be added, similar to the 4.0 update of SilverAzide's gadgets. Users will be able to go load these variants, configure the HWiNFO IDs, and be ready to go.

All settings in the GPU Meter settings skin will only affect the "GPU0" GPU Meter. The other three GPU Meters will have their own settings files, which have to be manually edited to change. Instructions on changing the variables will be included in those files.

### To-do
- [x] Delete dual GPU variant
- [x] Move GPU Meter into "GPU0" subfolder
- [x] Change path references in stylesheet
- [x] Update settings system code to stop using meter groups instead of meter names
- [x] Copy GPU Meter into "GPU1", "GPU2", and "GPU3" subfolders
- [x] Copy GpuSettings.inc file into four distinct files
- [x] Change variable file references for GPU Meter variants
- [x] Add variant settings files to settings backup script

**Comment by raiguard** [comment]
Done!
