### ISSUE TITLE
Use new MouseAction State Bangs

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#87]
The newest Rainmeter beta implemented [MouseAction State Bangs](https://docs.rainmeter.net/manual-beta/bangs/#MouseAction). This is perfect for disabling toggle buttons when an option is unavailable (e.g. HWiNFO is unavailable), because right now every mouseaction needs to be manually rewritten in !SetOption bangs. This change will greatly simplify the act of disabling toggle buttons in the settings skins.

### To-do
- [x] Add HWiNFO-affected toggle buttons to 'HwinfoButtons' group
- [x] Bulk disable/enable mouseactions for HwinfoButtons in HWiNFO detection measure
- [x] Add hover effect to all toggle buttons
