### ISSUE TITLE
Network Interface Options

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#90]
Network Meter will gain support for network interface options - choosing which specific network interfaces to monitor, rather than relying solely on Rainmeter's "best" option. This will both increase accuracy, and allow one to monitor specific adapters that normally wouldn't be included in network traffic (i.e. Xbox controller communications).

## To-do
- [x] Implement interface options in Network Meter settings
- [x] Add SilverAzide's auto-configure methods
- [x] Update Network Meter to support the new interface format
- [x] Update Network Meter Pro to support the new interface format

**Comment by raiguard** [comment]
Done!
