### ISSUE TITLE
Advanced Process Usage Data

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#91]
Process Meter will gain support for monitoring individual processes as determined by the user. Stats for CPU usage, RAM usage, Network usage, GPU usage, VRAM usage, and Disk usage over time will be tracked and displayed.

This functionality will be able to auto-initiate when that program is started, if the user wishes. Alternatively, it can be enabled, disabled, or reset at will.

This individual process tracking will support logging, allowing you to go back through and check for abnormalities in the usage. I am also considering adding the ability to replay these logs in the advanced monitor, so you can review it without having to stare at a sheet of numbers.

Finally, process meter itself will receive a redesign: the user can customize what appears in each column in the skin. For example, they could choose to display CPU usage and disk usage, rather than the default CPU usage and RAM utilization. Choosing what appears in the names column will determine how the list is sorted.

## To-do
- [x] Create debug skin that gathers all of the information for a specific process and displays it
- [ ] Implement file logging and log management
- [ ] Implement debug skin UI, copy for other four processes
- [ ] Update process meter with customizable columns

**Comment by raiguard** [comment]
So I have been putting off this feature for a long long time now because it seemed rather daunting. In reality, it really isn't, but it seems so to me for some reason.

So, while I am at work doing absolutely nothing (being a head lifeguard is awesome!), I figured I may as well lay out exactly what I plan to do with these features.

### Task Manager
I want to create a "task manager" applet that will display detailed information for each process, similar to the real task manager. You will be able to see CPU, RAM, GPU, VRAM, and disk IO usage for each process. Also similar to task manager, you will be able to click a category's name to sort the processes by that category.

This applet is what will also handle the logging. The actual process meter will be a "preview" of what Task Manager will tell you, but in order to specifically log statistics, you will need to open Task Manager and click the log button.

### Process Monitor
Process Monitor is a very different thing from Process Meter. While Process Meter, combined with Task Manager, will track multiple processes and sort them, Process Monitor will track specific process' stats and give more detailed views for them.

More specifically, you can choose a specific process to monitor. Once your selection is made, it will instantly begin tracking statistics for that process, and will automatically log them as well. For each stat (CPU, RAM, GPU, VRAM, and disk IO), you will see individual line graphs and statistics. Among the statistics will be the current value, session average, session peak low, and session peak high.

Process Monitor will be useful for tracking how taking certain actions in a program can affect its statistics.

#### Replaying logs (tentative)
I am also considering adding the ability to "replay" log files in Process Monitor. Using this, you could leave process monitor running while you're away, and let it track stats. Then, once a session is complete, you could "replay" the log, allowing you to scroll and scrub through the session and see the stats that it logged while you were away.

This feature would be very cool to have, but would be an absolute nightmare to implement, so it's staying on the "tentative" list for now.

**Comment by raiguard** [comment]
After much procrastinating, I have finally began work on Process Monitor. Here is a (very early) screenshot, for your viewing pleasure!

![2018-11-28 21_12_21-d__settings_caleb_rainmeter_skins_moderngadgets_processmeter_processmonitor_proc](https://user-images.githubusercontent.com/3515394/49198851-67414a00-f352-11e8-9eae-f4b13b08501b.png)

**Comment by Shrekmachine** [comment]
Is it planned that it will show the sum of all processes as well?

**Comment by raiguard** [comment]
Task manager will do that, not Process Monitor. Process Monitor is for monitoring an individual process in detail, while Task Manager will monitor all processes in slightly less detail.

**Comment by Shrekmachine** [comment]
Can it show the summary of CPU, RAM, Disk, GPU and VRAM?

**Comment by raiguard** [comment]
Yes.

**Comment by raiguard** [comment]
State of this: It was a good plan, but I'm postponing it past v1.5 due to complete lack of enthusiasm to work on it... Sorry Shrekmachine, I've failed you. :(

**Comment by raiguard** [comment]
This is also never going to happen. :/
