### ISSUE TITLE
Audio Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#92]
This gadget will allow you to control and see information on audio that is playing. Audio controls will include play, pause, next track, previous track, shuffle, repeat, and volume controls. If the user does not wish to control music tracks, the gadget will simply control computer audio.

Additionally, the gadget will display a basic visualizer along the bottom edge.

## To-do
- [x] Gadget fundamentals
- [x] Audio visualizer
- [x] Volume controls
- [x] Drag volume bar to move it
- [x] Configuration skin
#### NowPlaying Controls:
- [x] Album art
- [x] Title, artist, album, with marquee
- [x] Progress bar
- [x] Progress bar interaction (scrubbing through a song)
- [x] Progress & remaining time in song
- [x] Generic controls: previous, play, pause, next, shuffle, repeat
- [x] Accommodations for scaling
- [x] WebNowPlaying support

**Comment by raiguard** [comment]
State of this:

I would like to find a way to make the volume slider draggable, but I'm not getting my hopes up. As for the NowPlaying controls, I would like to be able to use container meters to make the text Marquee, but currently container meters do not work with scaling.

Other changes will include being able to change the headset icon to a speaker icon, and animation for the volume slider when you hover over it.

**Comment by Shrekmachine** [comment]
Probaly not that important as I was not recognizing any bad behaviour... 
From the Rainmeter Log: WebNowPlaing.dll - Error converting volume to integer, volume was:69.21628964857962

**Comment by raiguard** [comment]
Yeah, that's not something I can fix. That's up to the plugin developer. :(

**Comment by raiguard** [comment]
With dragging support added to the volume and song progress sliders, the only thing left to do is to figure out how to add scaling support to the media cover art and track info, and Audio Meter will be pretty much complete! :D

**Comment by raiguard** [comment]
Until containers are updated to support working with TransformationMatrix, you won't be able to use the standard version of the track info at any scale. If you set the scale factor to anything besides 1, then an alternate form of the track info will be used, one that does not use container meters. This results in the album art always having square corners, and the text staying still rather than marqueeing. :(

Now that scaling accomodations have been implemented, Audio Meter is now complete until such time as containers are updated. This issue will be closed once the next beta releases!

**Comment by raiguard** [comment]
Beta 9 is out!

**Comment by co5mo** [comment]
i use chrome (yt) and spotify app can this be dynamic too? whatever source is broadcasting?
