### ISSUE TITLE
Weather Meter

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#93]
This gadget will display the current weather. It will display a vast majority of the information gathered from the weather.com WxDataWeather feed, plus a bit more. Major features include current conditions, a sky dial showing the sun and moon, sunrise/sunset and moonrise/moonset times, and a moon phase visualization. Additionally, the gadget will include a detailed five-day forecast in a flyout, which can be accessed by clicking the weather condition icon.

Lastly, the gadget will support a small mode, where it will only display basic information until hovered over, where it will display everything else.

## To-do
- [x] Gadget base
- [x] Basic information
- [x] Moon phase
- [x] UV index colors and chart
- [x] Sun chart
- [x] Fix moon rise/set time calculations (tentative)
- [x] Time and date preference settings
- [x] High, low, and feels-like temperatures
- [x] Air pressure
- [x] Visual refinements (perhaps colored text?)
- [x] Severe weather alerts
- [x] Settings skin
  - [x] Proper location finder (search for city, rather than manually typing a code)
- [x] Five-day forecast

**Comment by raiguard** [comment]
State of this:

Weather Meter itself is pretty much complete. The only thing left to do is the seven-day forecast. I am struggling to find a good design for this so it's going to take a while.

**Comment by raiguard** [comment]
Not closing this issue QUITE yet since there are a few more things I want to do with the forecast. But it's almost there!

**Comment by raiguard** [comment]
The forecast is now complete! There still seems to be an issue with the sun/moon altitudes in Australia, which I'll have to look at, but it is functionally finished!

**Comment by raiguard** [comment]
Here's some screenshots:

![2019-02-16 11_50_13](https://user-images.githubusercontent.com/3515394/52904215-369cde00-31e6-11e9-839f-2feffceff235.png)
![2019-02-16 11_51_40](https://user-images.githubusercontent.com/3515394/52904217-369cde00-31e6-11e9-87df-7147a90d7c04.png)

**Comment by raiguard** [comment]
With the release of v1.5.0-beta.10, this is now complete! :D
