### ISSUE TITLE
Network Meter: WiFi strength and LAN connection

### ISSUE THREAD

**Issue by raiguard** [raiguard/ModernGadgets#95]
Network Meter will receive support for monitoring WiFi signal strength, and distinguishing LAN connections vs. Internet connections.

## To-do:
- [x] Get WiFi icon working in a test skin
- [x] Add logic for LAN vs. WAN connections
- [x] Add logic for switching the icon between ethernet, WiFi, LAN, or disconnected
- [x] Determine what the final icons are going to be
- [x] Implement into both Network Meters

**Comment by raiguard** [comment]
(Finally) done!
